#!/system/bin/sh
echo -n "警告: 该功能将会彻底删除日志/镜像/备份等所有不属于初始脚本根目录的数据 请确认是否删除[Y/n]"
read rm
case $rm in
Y)
sleep 0.001
;;
y)
sleep 0.001
;;
*)
echo "已停止脚本..."
;;
esac
# 清理脚本
rm -rf ./img/*
rm -rf ./log/*
rm -rf ./allimg/*
rm -rf ./fkimgs/*
rm -rf ./*.img
rm -rf ./*.bak
echo "清理完成..."
exit 0